### ISSUE TITLE
Create .DEREK.yml as per faas-cli

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/python3-debian#4]
* Create .DEREK.yml as per faas-cli repo

This enables Derek to work here

**Comment by sameetn** [comment]
What is the purpose of this file? Sorry ... am new to this one.

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-cli/blob/master/.DEREK.yml

**Comment by sameetn** [comment]
I can attempt this as I get home
